#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

BASE_IMAGE="${BASE_IMAGE:-registry.fedoraproject.org/fedora-minimal:latest}"

if [ -z "${DOCKER_HOST:-}" ]; then
    export PINP_ENGINE_UID=1000
    PINP_HOME="${PINP_ENGINE_HOME:-/var/lib/pbdc-pinp/home}"

    echo "=== pinp: rootless engine for uid $PINP_ENGINE_UID ==="
    PINP_ENV="$(bash scripts/pinp-up.sh)"
    PINP_SOCKET="$(printf '%s\n' "$PINP_ENV" | sed -n 's/^PINP_SOCKET=//p')"
    PINP_RUNTIME_DIR="$(printf '%s\n' "$PINP_ENV" | sed -n 's/^PINP_RUNTIME_DIR=//p')"
    PINP_SOCKET_DIR="$(printf '%s\n' "$PINP_ENV" | sed -n 's/^PINP_SOCKET_DIR=//p')"

    (
        setpriv --reuid="$PINP_ENGINE_UID" --regid="$PINP_ENGINE_UID" --init-groups \
            env HOME="$PINP_HOME" XDG_RUNTIME_DIR="$PINP_RUNTIME_DIR" \
            XDG_CONFIG_HOME="$PINP_HOME/.config" XDG_DATA_HOME="$PINP_HOME/.local/share" \
            podman system service --time=0 "unix://$PINP_SOCKET_DIR/podman.sock"
    ) >/var/log/pbdc-pinp-service.log 2>&1 < /dev/null &
    PINP_PID=$!

    echo "=== pinp: waiting for $PINP_SOCKET"
    for _ in $(seq 1 60); do
        [ -S "$PINP_SOCKET_DIR/podman.sock" ] && break
        sleep 1
    done
    if [ ! -S "$PINP_SOCKET_DIR/podman.sock" ]; then
        echo "=== pinp: ERROR service socket never appeared (see /var/log/pbdc-pinp-service.log)"
        exit 1
    fi
    echo "=== pinp: service up"

    export DOCKER_HOST="$PINP_SOCKET"
    export XDG_RUNTIME_DIR="$PINP_RUNTIME_DIR"
    echo "DOCKER_HOST=$DOCKER_HOST"
    echo "XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR"

    declare -A PINP_REF
    CUR_TAG=""
    while IFS= read -r LINE; do
        case "$LINE" in
            PINP_IMAGE_TAG=*) CUR_TAG="${LINE#PINP_IMAGE_TAG=}" ;;
            PINP_IMAGE_REF=*) [ -n "$CUR_TAG" ] && PINP_REF["$CUR_TAG"]="${LINE#PINP_IMAGE_REF=}" ;;
        esac
    done <<< "$PINP_ENV"

    restore_image_refs() {
        for TAG in "${!PINP_REF[@]}"; do
            for FILE in test/*/scenarios.json; do
                sed -i "s|${PINP_REF[$TAG]}|$TAG|g" "$FILE"
            done
        done
    }
    trap 'kill "$PINP_PID" 2>/dev/null || true; restore_image_refs' EXIT

    for TAG in "${!PINP_REF[@]}"; do
        echo "=== pinp: digest ref $TAG -> ${PINP_REF[$TAG]}"
        for FILE in test/*/scenarios.json; do
            sed -i "s|$TAG|${PINP_REF[$TAG]}|g" "$FILE"
        done
        [ "$TAG" = "registry.fedoraproject.org/fedora-minimal:latest" ] && BASE_IMAGE="${PINP_REF[$TAG]}"
    done
    echo "=== pinp: base image = $BASE_IMAGE"
else
    echo "DOCKER_HOST=$DOCKER_HOST (external, no pinp boot)"
fi

export ROOT BASE_IMAGE

AUTOGENERATED_CHAINS=(
    "with-base"
    "git with-base"
    "podman with-base"
    "podman-in-podman podman with-base"
    "podman-outside-of-podman podman with-base"
    "podman-docker-shim podman with-base"
    "with-podman podman-docker-shim podman-in-podman podman-outside-of-podman podman with-base"
    "nvm with-base"
    "node nvm with-base"
    "dotagents node nvm with-base"
)

SCENARIO_FEATURES=(with-base podman node dotagents with-podman)

run_autogenerated() {
    for chain in "${AUTOGENERATED_CHAINS[@]}"; do
        echo "=== autogenerated: $chain (base: $BASE_IMAGE) ==="
        devcontainer features test --skip-scenarios -p . -f $chain --base-image "$BASE_IMAGE"
    done
}

run_scenarios() {
    for feature in "${SCENARIO_FEATURES[@]}"; do
        echo "=== scenarios: $feature ==="
        devcontainer features test --skip-autogenerated -p . -f "$feature"
    done
}

run_global() {
    echo "=== global scenarios ==="
    devcontainer features test --global-scenarios-only -p .
}

run_autogenerated
run_scenarios
run_global

echo "All feature tests passed."