#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

BASE_IMAGE="${BASE_IMAGE:-registry.fedoraproject.org/fedora-minimal:latest}"
: "${DOCKER_HOST:?DOCKER_HOST must point at a rootless podman socket (e.g. unix:///root/.poop/poop)}"

export ROOT BASE_IMAGE

# Mirrors the official devcontainers/features test-all.yaml, adapted to this
# collection: Fedora-only autogenerated tests (full dep chain, since relative
# dependsOn refs are not published to an OCI registry), per-feature scenarios,
# and global scenarios from test/_global.

AUTOGENERATED_CHAINS=(
    "with-base"
    "git with-base"
    "podman with-base"
    "podman-in-podman podman with-base"
    "poop podman with-base"
    "with-podman podman-in-podman poop podman with-base"
    "nvm with-base"
    "node nvm with-base"
    "dotagents node nvm with-base"
)

SCENARIO_FEATURES=(with-base podman node dotagents with-podman)

run_autogenerated() {
    for chain in "${AUTOGENERATED_CHAINS[@]}"; do
        echo "=== autogenerated: $chain (base: $BASE_IMAGE) ==="
        devcontainer features test --skip-scenarios -p . -f $chain --base-image "$BASE_IMAGE"
    done
}

run_scenarios() {
    for feature in "${SCENARIO_FEATURES[@]}"; do
        echo "=== scenarios: $feature ==="
        devcontainer features test --skip-autogenerated -p . -f "$feature"
    done
}

run_global() {
    echo "=== global scenarios ==="
    devcontainer features test --global-scenarios-only -p .
}

run_autogenerated
run_scenarios
run_global

echo "All feature tests passed."